# Generated by Django 4.2.17 on 2024-12-09 16:54

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(upload_to=images.models.upload_to)),
                ('category', models.CharField(max_length=20)),
                ('ai_category', models.CharField(max_length=20)),
            ],
        ),
    ]
